# .streamlit/config.toml

[theme]
# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
primaryColor = "#02abde"

# Background color for the main content area.
backgroundColor = "#0e1117"

# Background color for sidebar and most interactive widgets.
secondaryBackgroundColor = "#262730"

# Color used for almost all text.
textColor = "#fafafa"

# Font family for all text in the app.
# One of "sans serif", "serif", or "monospace".
font = "sans serif"